// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __cbsg_hh__
#define __cbsg_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_cbsg
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_cbsg
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_cbsg
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CorbaCBSG

_CORBA_MODULE_BEG

  struct timestamped_Sentence {
    typedef _CORBA_ConstrType_Variable_Var<timestamped_Sentence> _var_type;

    
    ::CORBA::Long timestamp;

    ::CORBA::String_member sentence;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef timestamped_Sentence::_var_type timestamped_Sentence_var;

  typedef _CORBA_ConstrType_Variable_OUT_arg< timestamped_Sentence,timestamped_Sentence_var > timestamped_Sentence_out;

#ifndef __CorbaCBSG_mCBSG__
#define __CorbaCBSG_mCBSG__
  class CBSG;
  class _objref_CBSG;
  class _impl_CBSG;
  
  typedef _objref_CBSG* CBSG_ptr;
  typedef CBSG_ptr CBSGRef;

  class CBSG_Helper {
  public:
    typedef CBSG_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_CBSG, CBSG_Helper> CBSG_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_CBSG,CBSG_Helper > CBSG_out;

#endif

  // interface CBSG
  class CBSG {
  public:
    // Declarations for this interface type.
    typedef CBSG_ptr _ptr_type;
    typedef CBSG_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_CBSG :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    timestamped_Sentence* createTimestampedSentence();
    char* createSentence();
    char* createWorkshop();
    char* createShortWorkshop();
    char* createFinancialReport();

    // Constructors
    inline _objref_CBSG()  { _PR_setobj(0); }  // nil
    _objref_CBSG(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_CBSG();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_CBSG(const _objref_CBSG&);
    _objref_CBSG& operator = (const _objref_CBSG&);
    // not implemented

    friend class CBSG;
  };

  class _pof_CBSG : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_CBSG() : _OMNI_NS(proxyObjectFactory)(CBSG::_PD_repoId) {}
    virtual ~_pof_CBSG();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_CBSG :
    public virtual omniServant
  {
  public:
    virtual ~_impl_CBSG();

    virtual timestamped_Sentence* createTimestampedSentence() = 0;
    virtual char* createSentence() = 0;
    virtual char* createWorkshop() = 0;
    virtual char* createShortWorkshop() = 0;
    virtual char* createFinancialReport() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_CorbaCBSG
_CORBA_MODULE_BEG

  class CBSG :
    public virtual CorbaCBSG::_impl_CBSG,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~CBSG();

    inline ::CorbaCBSG::CBSG_ptr _this() {
      return (::CorbaCBSG::CBSG_ptr) _do_this(::CorbaCBSG::CBSG::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CorbaCBSG
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
CorbaCBSG::CBSG::_marshalObjRef(::CorbaCBSG::CBSG_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_cbsg
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_cbsg
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_cbsg
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_cbsg
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_cbsg
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_cbsg
#endif

#endif  // __cbsg_hh__

